### ISSUE TITLE
Crash when the connection die

### ISSUE THREAD

**Issue by chuanhaisoft** [yupswing/akifox-asynchttp#1] opened 2015-04-23 06:15 UTC
1.
        var request = new AsyncHttpRequest("http://www.00000.com/123.php",
                               function(response:AsyncHttpResponse):Void {
                                    if (response.isOK) {
                                        trace(response.content);
                                        trace('DONE (HTTP STATUS ${response.status})');
                                    } else {
                                        trace('ERROR (HTTP STATUS ${response.status})');
                                    }
                               }  
                          );
        request.send();

2.
123.php: <?php    sleep(60); ?>

3.

After 10 seconds
Disconnect the phone network
then app crashes

**Comment by yupswing** [comment] 2015-04-23 09:45
Yes I can reproduce the bug also in neko.
It is an exception on the http request thread that is not handled and it stops the execution of the whole app.

I am working on it.
Thanks for the feedback

**Comment by yupswing** [comment] 2015-04-23 10:48
Fixed in 0.3.1

**Comment by yupswing** [comment] 2015-04-23 10:49
Can you confirm the issue is fixed for you?
I've released the update on haxelib

**Comment by chuanhaisoft** [comment] 2015-04-23 11:50
thank you for help

**Closed as completed** 2015-04-23 12:55 UTC
Labels: bug, all platforms
